//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/TouchInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchInput"",
    ""maps"": [
        {
            ""name"": ""touchInput1"",
            ""id"": ""78dca148-0361-4b34-b755-ecb54e2174a5"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""80b40f00-7828-42b1-850a-c932a9a41e4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fb667ff4-e1a0-47ec-8f8c-f4923c546eb8"",
                    ""path"": ""<Touchscreen>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // touchInput1
        m_touchInput1 = asset.FindActionMap("touchInput1", throwIfNotFound: true);
        m_touchInput1_Click = m_touchInput1.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // touchInput1
    private readonly InputActionMap m_touchInput1;
    private List<ITouchInput1Actions> m_TouchInput1ActionsCallbackInterfaces = new List<ITouchInput1Actions>();
    private readonly InputAction m_touchInput1_Click;
    public struct TouchInput1Actions
    {
        private @TouchInput m_Wrapper;
        public TouchInput1Actions(@TouchInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_touchInput1_Click;
        public InputActionMap Get() { return m_Wrapper.m_touchInput1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchInput1Actions set) { return set.Get(); }
        public void AddCallbacks(ITouchInput1Actions instance)
        {
            if (instance == null || m_Wrapper.m_TouchInput1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchInput1ActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(ITouchInput1Actions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(ITouchInput1Actions instance)
        {
            if (m_Wrapper.m_TouchInput1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchInput1Actions instance)
        {
            foreach (var item in m_Wrapper.m_TouchInput1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchInput1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchInput1Actions @touchInput1 => new TouchInput1Actions(this);
    public interface ITouchInput1Actions
    {
        void OnClick(InputAction.CallbackContext context);
    }
}
